package com.goorm.springmissionsplayground.mission05_spring_db.task06_data_access_exception_handling.repository;

import com.goorm.springmissionsplayground.mission05_spring_db.task06_data_access_exception_handling.domain.JdbcMember;
import com.goorm.springmissionsplayground.mission05_spring_db.task06_data_access_exception_handling.exception.JdbcDataAccessException;
import jakarta.annotation.PostConstruct;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.sql.DataSource;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Repository;

@Repository
public class JdbcMemberRepository {

    private static final String TABLE_NAME = "mission05_task06_members";

    private final DataSource dataSource;

    public JdbcMemberRepository(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @PostConstruct
    void initializeTable() {
        String sql = """
                create table if not exists mission05_task06_members (
                    id bigint generated by default as identity primary key,
                    name varchar(100) not null,
                    email varchar(255) not null unique,
                    grade varchar(50) not null
                )
                """;

        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        } catch (SQLException exception) {
            throw new IllegalStateException("task06 JDBC 테이블 초기화에 실패했습니다.", exception);
        }
    }

    public JdbcMember save(String name, String email, String grade) {
        String sql = """
                insert into mission05_task06_members (name, email, grade)
                values (?, ?, ?)
                """;

        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            preparedStatement.setString(1, name);
            preparedStatement.setString(2, email);
            preparedStatement.setString(3, grade);
            preparedStatement.executeUpdate();

            try (ResultSet generatedKeys = preparedStatement.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    return new JdbcMember(generatedKeys.getLong(1), name, email, grade);
                }
            }

            throw new JdbcDataAccessException(
                    HttpStatus.INTERNAL_SERVER_ERROR,
                    "KEY_GENERATION_FAILED",
                    "회원 저장은 완료되었지만 생성된 ID를 확인하지 못했습니다.",
                    null,
                    null
            );
        } catch (SQLException exception) {
            throw translateException(
                    exception,
                    "이미 등록된 이메일입니다. 다른 이메일을 입력해주세요.",
                    "회원 저장 중 데이터베이스 오류가 발생했습니다. 잠시 후 다시 시도해주세요."
            );
        }
    }

    public Optional<JdbcMember> findById(Long id) {
        String sql = """
                select id, name, email, grade
                from mission05_task06_members
                where id = ?
                """;

        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.setLong(1, id);

            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    return Optional.of(mapMember(resultSet));
                }
                return Optional.empty();
            }
        } catch (SQLException exception) {
            throw translateException(
                    exception,
                    "회원 조회 중 데이터베이스 오류가 발생했습니다. 잠시 후 다시 시도해주세요."
            );
        }
    }

    public List<JdbcMember> findAll() {
        String sql = """
                select id, name, email, grade
                from mission05_task06_members
                order by id asc
                """;

        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql);
             ResultSet resultSet = preparedStatement.executeQuery()) {
            List<JdbcMember> members = new ArrayList<>();
            while (resultSet.next()) {
                members.add(mapMember(resultSet));
            }
            return members;
        } catch (SQLException exception) {
            throw translateException(
                    exception,
                    "회원 목록 조회 중 데이터베이스 오류가 발생했습니다. 잠시 후 다시 시도해주세요."
            );
        }
    }

    public void executeBrokenSelect() {
        String sql = """
                select missing_column
                from mission05_task06_members
                """;

        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.executeQuery();
        } catch (SQLException exception) {
            throw translateException(
                    exception,
                    "잘못된 SQL 실행으로 데이터를 조회하지 못했습니다. SQL 문과 컬럼명을 다시 확인해주세요."
            );
        }
    }

    public void deleteAll() {
        String sql = "delete from " + TABLE_NAME;

        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.executeUpdate();
        } catch (SQLException exception) {
            throw translateException(
                    exception,
                    "테스트 데이터 정리 중 데이터베이스 오류가 발생했습니다. 잠시 후 다시 시도해주세요."
            );
        }
    }

    private JdbcMember mapMember(ResultSet resultSet) throws SQLException {
        return new JdbcMember(
                resultSet.getLong("id"),
                resultSet.getString("name"),
                resultSet.getString("email"),
                resultSet.getString("grade")
        );
    }

    private JdbcDataAccessException translateException(SQLException exception, String fallbackMessage) {
        return translateException(exception, null, fallbackMessage);
    }

    private JdbcDataAccessException translateException(
            SQLException exception,
            String duplicateMessage,
            String fallbackMessage
    ) {
        if (isIntegrityConstraintViolation(exception) && duplicateMessage != null) {
            return new JdbcDataAccessException(
                    HttpStatus.CONFLICT,
                    "DUPLICATE_EMAIL",
                    duplicateMessage,
                    exception.getSQLState(),
                    exception
            );
        }

        return new JdbcDataAccessException(
                HttpStatus.INTERNAL_SERVER_ERROR,
                "JDBC_PROCESSING_ERROR",
                fallbackMessage,
                exception.getSQLState(),
                exception
        );
    }

    private boolean isIntegrityConstraintViolation(SQLException exception) {
        String sqlState = exception.getSQLState();
        return sqlState != null && sqlState.startsWith("23");
    }
}
