package com.goorm.springmissionsplayground.mission05_spring_db.task07_transaction_isolation_level.repository;

import com.goorm.springmissionsplayground.mission05_spring_db.task07_transaction_isolation_level.domain.IsolationInventoryItem;
import jakarta.annotation.PostConstruct;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.Objects;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

@Repository
public class IsolationInventoryRepository {

    private static final String TABLE_NAME = "mission05_task07_inventory";
    private static final RowMapper<IsolationInventoryItem> ITEM_ROW_MAPPER = (resultSet, rowNum) -> new IsolationInventoryItem(
            resultSet.getLong("id"),
            resultSet.getString("product_name"),
            resultSet.getInt("quantity")
    );

    private final JdbcTemplate jdbcTemplate;

    public IsolationInventoryRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @PostConstruct
    void initializeTable() {
        jdbcTemplate.execute("""
                create table if not exists mission05_task07_inventory (
                    id bigint generated by default as identity primary key,
                    product_name varchar(100) not null,
                    quantity integer not null
                )
                """);
    }

    public Long save(String productName, int quantity) {
        KeyHolder keyHolder = new GeneratedKeyHolder();

        jdbcTemplate.update(connection -> {
            PreparedStatement preparedStatement = connection.prepareStatement(
                    "insert into " + TABLE_NAME + " (product_name, quantity) values (?, ?)",
                    Statement.RETURN_GENERATED_KEYS
            );
            preparedStatement.setString(1, productName);
            preparedStatement.setInt(2, quantity);
            return preparedStatement;
        }, keyHolder);

        return Objects.requireNonNull(keyHolder.getKey(), "task07 재고 ID 생성에 실패했습니다.").longValue();
    }

    public IsolationInventoryItem findById(Long itemId) {
        return jdbcTemplate.query(
                "select id, product_name, quantity from " + TABLE_NAME + " where id = ?",
                ITEM_ROW_MAPPER,
                itemId
        ).stream()
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("재고 데이터를 찾을 수 없습니다. id=" + itemId));
    }

    public int findQuantityById(Long itemId) {
        return findById(itemId).quantity();
    }

    public void updateQuantity(Long itemId, int quantity) {
        int updatedCount = jdbcTemplate.update(
                "update " + TABLE_NAME + " set quantity = ? where id = ?",
                quantity,
                itemId
        );

        if (updatedCount == 0) {
            throw new IllegalArgumentException("수정할 재고 데이터를 찾을 수 없습니다. id=" + itemId);
        }
    }

    public void deleteAll() {
        jdbcTemplate.update("delete from " + TABLE_NAME);
    }
}
