package com.goorm.springmissionsplayground.mission05_spring_db.task08_jdbctemplate_query.repository;

import com.goorm.springmissionsplayground.mission05_spring_db.task08_jdbctemplate_query.domain.JdbcTemplateBook;
import jakarta.annotation.PostConstruct;
import java.util.List;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

@Repository
public class JdbcTemplateBookRepository {

    private static final String TABLE_NAME = "mission05_task08_books";
    private static final RowMapper<JdbcTemplateBook> BOOK_ROW_MAPPER = (resultSet, rowNum) -> new JdbcTemplateBook(
            resultSet.getLong("id"),
            resultSet.getString("title"),
            resultSet.getString("author"),
            resultSet.getString("level")
    );

    private final JdbcTemplate jdbcTemplate;

    public JdbcTemplateBookRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @PostConstruct
    void initializeTableAndSampleData() {
        jdbcTemplate.execute("""
                create table if not exists mission05_task08_books (
                    id bigint generated by default as identity primary key,
                    title varchar(100) not null,
                    author varchar(50) not null,
                    level varchar(30) not null
                )
                """);
        resetSampleData();
    }

    public List<JdbcTemplateBook> findAll() {
        return jdbcTemplate.query(
                """
                select id, title, author, level
                from mission05_task08_books
                order by id asc
                """,
                BOOK_ROW_MAPPER
        );
    }

    public void resetSampleData() {
        jdbcTemplate.execute("truncate table " + TABLE_NAME + " restart identity");
        jdbcTemplate.batchUpdate(
                "insert into " + TABLE_NAME + " (title, author, level) values (?, ?, ?)",
                List.of(
                        new Object[]{"스프링 입문", "김스프링", "BEGINNER"},
                        new Object[]{"JdbcTemplate 핵심", "이데이터", "INTERMEDIATE"},
                        new Object[]{"트랜잭션 실전", "박트랜잭션", "ADVANCED"}
                )
        );
    }
}
